
FROM node:16 AS build

WORKDIR /app

COPY ClientApp/package*.json ./

RUN npm install

COPY ClientApp/ .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 44402
CMD ["nginx", "-g", "daemon off;"]
